/**
 * @file hasher.hpp
 * @author Steven Swanbeck (steven.swanbeck@gmail.com)
 * @brief class to generate spatial hashes for hylacomylus' storage and retrieval
 * @version 0.1
 * 
 * @copyright Copyright (c) 2024
 * 
 */
#pragma once

// CPP
#include <cstdint>
#include <array>
#include <map>

#include <Eigen/Dense>

// Custom
#include "chunk.hpp"
#include "utils.hpp"

namespace hylacomylus {

// --------------------------------------------------------------------------------------
// & Class for generating hashes to store and access chunks
// --------------------------------------------------------------------------------------

/** @class ChunkHasher
 * @brief Generates unique 32-bit integer hashes corresponding to voxels in space to be populated by collected data
 * 
 * @var discretization the voxel leaf size, expressed in meters
 * @var hashSigns a map between ints representing unique sign conditions (3D space with each number either +/-, so (2^3) = 8 unique integers required to express all possible sign combinations) and a 3-dimensional array containing (+/-)1 scalars to be applied to each number in the x,y,z directions; the 8-bit integers used as keys are composed into the 32-bit integers that define each hash
 * @var signHashes the inverse of hashSigns; maps each array of (+/-)1 scalars to a unique 8-bit integer to be composed as part of the unique 32-bit hash for each voxel
 * 
 * @note hashes are generated as unsigned 32-bit integers that can be subdivided into four unique 8-bit integers - one for each x,y,z block and one describing the set of signs for each of the x,y,z block displacements
 * @note hashes are deterministic, meaning using the same voxel discretization with the same location in space will always generate the same hash, allowing data to be dumped to disk and immediately recycled at the next node lifetime 
 * @warning the maximum map size is a function of this discretization -> max_size_(x/y/z) = discretization * 256, where the map is centered about the origin (ie. with a discretization size of 1 m, the maximum size map that can be hashed is (-127 m : 128 m) in each of the x,y,z directions for a total volume of (discretization * 256) ^3); if a larger map size is required with a small discretization, consider making hashes 64-bit or 128-bit integers
 */
class ChunkHasher {
  public:
    /** 
     * @brief Construct a new Chunk Hasher object
     * 
     * @param discretization_size the voxel leaf size to be used to discretize the hashes
     * 
     * @warning refer to @warning in the description of @class ChunkHasher
     */
    ChunkHasher(int discretization_size) 
    {
        discretization = discretization_size;
        hash_signs = buildHashSigns();
        sign_hashes = buildSignHashes();
    }

    /**
     * @brief generates a deterministic unsigned 32-bit integer hash for a point in space
     * 
     * @param point point in space with x,y,z components
     * @return std::uint32_t hash corresponding to block in space
     */
    std::uint64_t generateHash(const Point &point)
    {
        return generateHash(Eigen::Vector3d(point.x, point.y, point.z));
    }

    /**
     * @brief generates a detemerministic unsigned 32-bit integer hash for a point in space
     * 
     * @param point point in space with x,y,z components
     * @return std::uint32_t hash corresponding to block in space
     */
    std::uint64_t generateHash(const Eigen::Vector3d &point) 
    {
        std::uint8_t n0 {sign_hashes[{valueSign(point.x()), valueSign(point.y()), valueSign(point.z())}]};
        std::uint16_t n1 = valueMagnitude(point.x());
        std::uint16_t n2 = valueMagnitude(point.y());
        std::uint16_t n3 = valueMagnitude(point.z());

        std::uint64_t hash = static_cast<std::uint64_t>(n0) |
                            (static_cast<std::uint64_t>(n1) << 16) | 
                            (static_cast<std::uint64_t>(n2) << 32) | 
                            (static_cast<std::uint64_t>(n3) << 48);
        return hash;
    }

    /**
     * @brief parses a hash to produce a point within the associated box in space
     * 
     * @param hash in the form generated by this class
     * @return Point with x,y,z components
     * 
     * @warning information about a point is lost when a hash is generated, so the exact point location cannot be recovered from a hash; instead only the neighborhood or voxel box that a point falls within can be recovered. Thus, this function is likely only useful for debugging purposes 
     */
    Eigen::Vector3d parseHash(const std::uint64_t &hash)
    {
        Eigen::Vector3d p;
        std::uint8_t n0 {static_cast<std::uint8_t>(hash & 0xFF)};
        std::array<std::int8_t, 3> signs {hash_signs[n0]};
        p.x() = static_cast<float>(static_cast<std::uint16_t>((hash >> 16) & 0xFF)) * signs[0] * discretization;
        p.y() = static_cast<float>(static_cast<std::uint16_t>((hash >> 32) & 0xFF)) * signs[1] * discretization;
        p.z() = static_cast<float>(static_cast<std::uint16_t>((hash >> 48) & 0xFF)) * signs[2] * discretization;
        return p;
    }

  private:
    int discretization;
    std::map<std::uint8_t, std::array<std::int8_t, 3>> hash_signs;
    std::map<std::array<std::int8_t, 3>, std::uint8_t> sign_hashes;

    /**
     * @brief constructs a map that maps unsigned 8-bit numbers to arrays of sign scalars
     * 
     * @return std::map<std::uint8_t, std::array<std::int8_t, 3>> map to be stored as class member
     */
    std::map<std::uint8_t, std::array<std::int8_t, 3>> buildHashSigns() 
    {
        std::map<std::uint8_t, std::array<std::int8_t, 3>> hashSigns;
        hashSigns[0] = {1, 1, 1};
        hashSigns[1] = {-1, 1, 1};
        hashSigns[2] = {1, -1, 1};
        hashSigns[3] = {1, 1, -1};
        hashSigns[4] = {-1, -1, 1};
        hashSigns[5] = {-1, 1, -1};
        hashSigns[6] = {1, -1, -1};
        hashSigns[7] = {-1, -1, -1};
        return hashSigns;
    }

    /**
     * @brief constructs a map that maps arrays of sign scalars to unsigned 8-bit numbers
     * 
     * @return std::map<std::array<std::int8_t, 3>, std::uint8_t> 
     */
    std::map<std::array<std::int8_t, 3>, std::uint8_t> buildSignHashes() 
    {
        std::map<std::array<std::int8_t, 3>, std::uint8_t> signHashes;
        signHashes[{1, 1, 1}] = 0;
        signHashes[{-1, 1, 1}] = 1;
        signHashes[{1, -1, 1}] = 2;
        signHashes[{1, 1, -1}] = 3;
        signHashes[{-1, -1, 1}] = 4;
        signHashes[{-1, 1, -1}] = 5;
        signHashes[{1, -1, -1}] = 6;
        signHashes[{-1, -1, -1}] = 7;
        return signHashes;
    }

    /**
     * @brief returns the sign of input number
     * 
     * @param value x/y/z position component
     * @return std::int8_t either (-1) or (1) 
     */
    std::int8_t valueSign(float value) 
    {
        if (value < 0) {
            return -1;
        }
        return 1;
    }

    /**
     * @brief returns an unsigned 8-bit integer for the relative positioning of a voxel block that is composed into the generated hash
     * 
     * @param value x/y/z position component
     * @return std::uint8_t associated block index
     */
    std::uint16_t valueMagnitude(float value) 
    {
        return static_cast<std::uint16_t>(std::abs(value) / discretization);
    }
}; // class ChunkHasher

}
